apiVersion: v1
kind: Service
metadata:
  name: garage
spec:
  ports:
    - protocol: TCP
      port: 3900
      targetPort: 3900
      name: s3
    - protocol: TCP
      port: 3902
      targetPort: 3902
      name: web
    - protocol: TCP
      port: 3903
      targetPort: 3903
      name: admin
---
apiVersion: v1
kind: Endpoints
metadata:
  name: garage
subsets:
  - addresses:
      - ip: 10.0.0.9
    ports:
      - port: 3900
        name: s3
      - port: 3902
        name: web
      - port: 3903
        name: admin
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage
  labels:
    traefik-instance: internal
spec:
  hostnames:
    - garage.plexmox.com
  rules:
    - backendRefs:
        - kind: Service
          name: garage
          port: 3900
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: traefik
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-web
  labels:
    traefik-instance: internal
spec:
  hostnames:
    - garage-web.plexmox.com
  rules:
    - backendRefs:
        - kind: Service
          name: garage
          port: 3902
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: traefik
---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-admin
  labels:
    traefik-instance: internal
spec:
  hostnames:
    - garage-web.plexmox.com
  rules:
    - backendRefs:
        - kind: Service
          name: garage
          port: 3903
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: traefik
