apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kgateway
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: kubernetes/k3s/apps/networking/kgateway/chart
    repoURL: https://gitlab.com/henrywhitaker3/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.kgateway.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.kgateway.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
