generic:
  nameOverride: overseerr
  fullnameOverride: overseerr

  replicaCount: 1

  image:
    repository: sctx/overseerr
    pullPolicy: Always
    tag: latest

  service:
    port: 5055

  resources:
    requests:
      cpu: 50m
      memory: 256Mi

  httpRoute:
    enabled: true
    labels:
      traefik-instance: public
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: traefik
    rules:
      - port: 5055
        matches:
          - path:
              type: Prefix
              value: /

  ingress:
    enabled: false
    className: public
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.middlewares: media-overseerr@kubernetescrd
    hosts:
      - host: overseerr.plexmox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: overseerr-plexmox-com-tls
        hosts:
          - overseerr.plexmox.com

  pvc:
    enabled: true
    mountPath: /app/config
    storageClassName: longhorn
    size: 1Gi

  deploymentStrategy:
    type: Recreate

  probes:
    type: tcpSocket
    options:
      port: http

    initialDelaySeconds: 20

  config:
    TZ: Europe/London
