---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  labels:
    traefik-instance: internal
spec:
  gatewayClassName: internal
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: '*.henrywhitaker.com'
    name: henrywhitaker
    port: 8443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: wildcard-henrywhitaker-com-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    hostname: '*.plexmox.com'
    name: plexmox
    port: 8443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: wildcard-plexmox-com-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: '*.synthetigo.com'
    name: syntehtigo
    port: 8443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: wildcard-synthetigo-dev-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: Same
    name: web
    port: 8000
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    hostname: '*.yourbuild.com'
    name: yourbuild
    port: 8443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: wildcard-yourbuild-dev-tls
      mode: Terminate
status:
  addresses:
  - type: IPAddress
    value: 10.0.0.27
  conditions:
  - lastTransitionTime: "2025-11-14T20:24:54Z"
    message: Gateway successfully scheduled
    observedGeneration: 4
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2025-11-14T20:24:54Z"
    message: Gateway successfully scheduled
    observedGeneration: 4
    reason: Programmed
    status: "True"
    type: Programmed
  listeners:
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
    name: henrywhitaker
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
    name: plexmox
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
    name: syntehtigo
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
    name: web
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
  - attachedRoutes: 0
    conditions:
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    - lastTransitionTime: "2025-11-14T20:24:54Z"
      message: No error found
      observedGeneration: 4
      reason: Programmed
      status: "True"
      type: Programmed
    name: yourbuild
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
