apiVersion: v2
name: prompage
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: prompage-helm
    alias: prompage
    version: "v0.1.20"
    repository: oci://ghcr.io/henrywhitaker3
