apiVersion: v2
name: homie
description: homie manifests
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: generic
    version: "v1.3.21"
    repository: oci://ghcr.io/henrywhitaker3
