generic:
  nameOverride: homie
  fullnameOverride: homie

  replicaCount: 1

  image:
    repository: ghcr.io/brramble/homie
    pullPolicy: IfNotPresent
    tag: V1.4

  service:
    port: 5000

  probes:
    enabled: true
    type: httpGet
    options:
      path: /login
      port: http

  name:
    - name: DATABASE_PATH
      value: /app/data/homie.db
    - name: FLASK_DEBUG
      value: "false"
    - name: BASE_URL
      value: https://homie.plexmox.com
    - name: PORT
      value: "5000"
    - name: OIDC_ENABLED
      value: "true"
    - name: OIDC_BASE_URL
      value: https://auth.plexmox.com
    - name: ALLOWED_GROUPS
      value: "admin"
    - name: SESSION_COOKIE_SECURE
      value: "true"
    - name: LOG_LEVEL
      value: INFO
    - name: PYTHONUNBUFFERED
      value: "1"

  secrets:
    enabled: true
    key: homie-secrets
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect

  httpRoute:
    enabled: true
    labels:
      traefik-instance: public
    hostnames: [homie.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: traefik
    rules:
      - port: 5000
        matches:
          - path:
              type: PathPrefix
              value: /
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: auth-public

  pvc:
    enabled: true
    mountPath: /app/data
    size: "1Gi"
    storageClassName: longhorn
