apiVersion: v2
name: external-secrets
description: external-secrets chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: external-secrets
    repository: https://charts.external-secrets.io
    version: 0.12.1
