apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    version: 1.1.0
    namespace: external-secrets
    valuesFile: values.yaml

resources:
  - secrets
  - stores

patches:
  - path: patches/clustersecretstores.yaml
  - path: patches/secretstores.yaml
