netbird_setup_key: ENC[AES256_GCM,data:TSxAUO7fYDrIR9mdG2pY4fpxJI47HGgpOc98J2pXzgmRY8JV,iv:yl+GQsdFsq1OZVmzUta1gpxLzjd3T7e6JbV6uFtjg9E=,tag:s0k3x0jaxJH/7ps8LxQczA==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNk5UMEk4bjIzTGVVZmZ0
            UWJ3VzZiS0RySTBVdDNMMTE5eUdIdklLaVVVCkJFVHNMaWxKNGVWK2RrczJTN28v
            SnlkZDdyVmZoaGhTUThxOXQ2NTU5OWsKLS0tIHdJT3NiZkZLSG4xSzJibnMyQWZZ
            US9yV29odUVtZ1RRcmxCbEV4a2RKYUEKA5b9O/24ahXIZRPy/NY79b1mIPSQr+66
            Z/FM8uhwma5BLvjaSqnUJwU2LiwVqUQMW5UnLgrBrmHidKGO/OxqFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:12:55Z"
    mac: ENC[AES256_GCM,data:2ce+JHOz3jTm4inyVuUg1BwtY9PaVq1tgHT8kGf9uKG7xF20iYvl4JsdRNPYwR7YHc+2XgHXG0mLEcErcawBl7Gn7zRhC73otgbiPqnYvKhHOs/RtG8o/psBmCR5zB9i6uXxTcbyjeyoFwi7Wfn9Bf5c6DDfEW+H9dMNYWHYtMU=,iv:1P6mAU9xLnnAd30C02F71GnaezQNBgEBWlQNlhKApxs=,tag:uMswpidleFcjYo/cFjVUnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
