healthcheck: ENC[AES256_GCM,data:fMWPotGKMNEgJptLfMwbG/38qyS6411jxDY2J8QLI+WD7JvC2mgBte/KJgPVEOKDZC18/J0IBSY=,iv:t9WCKVcnjqVYLHjlQ5xPNgmAnbbE8OadQPUDzf8OZ5g=,tag:iXk1EyeaOP8ucnVyrDDR5A==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:353hutHbZmrqgkxeZwzacyNY5p1/wd6BeDJ4Vl2xnmfLiyWD,iv:oKqaRHWgoG+JkO0Kc1QHnNmpsXNQbuqcGr3jO9lQnBY=,tag:xl/5nM/Ppu7focwBOoJcZA==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cXJZVUQ1SjZ5dk5YTlZK
            TmxCbmpVYTZpNTM2cmxoQlpxaVN4NmowK1dBClN6RzY5cGc1TTYrejFTd21mNFU5
            djhIYmtyL0o1VDJQZVJaZ2JmVnJHSzgKLS0tIGdlV3VJWHRId1VwQi9jTy80d3JM
            bVI3N21Id2tHTkVrR0Q2SFhIdHo3a1UKaQLcVxS0zc/kLoGYSHeYl9/1CPwNcb+h
            VLlXry2w74rTCfVppy7fAFElsbR4NkhbnEC9Di/89X+WORAE4b+EWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:12:26Z"
    mac: ENC[AES256_GCM,data:6zLaylLw1WQM6/jErZ3OEkyE1pzED5YliaxSGCjNEVFKVJmEHEDIE80Ijw+zIIDkd/NF36ubhbhvxx4xiTd+T+DeziSnfVTdZpZtuYCkkVh5g/ZWse9oSLXQkJSls005XFQmsUQ6S9VZHqu78Pw3cKXGZl0hDjb1zPtBrIns354=,iv:W2hyCu+vCaVtYUzZd4MBWthUOIYID2Y1rnn05f73Nhs=,tag:p1EQwkFKpvVFLngTBzSzPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
