healthcheck: ENC[AES256_GCM,data:s5dKnKSc17sbTtL9jMt54woj6KBYjgUMoHz+QiiW+PBAGVJcZp1ib36HOBhid1DG2w61uzFIbFw=,iv:iJGD0UtIDehT8TRTRhfJbBRa7NM+zoenZP0leZlgGcc=,tag:5vffs7Svtfgh9gyr2+mi5Q==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:BZ8a8LVsEqfhsmBClFOo23oCzhUEM7aq+44m+gLlOnm4V3Vt,iv:2e8xhfav5QzJI3QX2zRKPtu54fCHuvJU1cmsoaO6d4Y=,tag:6GzklsmuNN9azf5b4tz17A==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cXJZVUQ1SjZ5dk5YTlZK
            TmxCbmpVYTZpNTM2cmxoQlpxaVN4NmowK1dBClN6RzY5cGc1TTYrejFTd21mNFU5
            djhIYmtyL0o1VDJQZVJaZ2JmVnJHSzgKLS0tIGdlV3VJWHRId1VwQi9jTy80d3JM
            bVI3N21Id2tHTkVrR0Q2SFhIdHo3a1UKaQLcVxS0zc/kLoGYSHeYl9/1CPwNcb+h
            VLlXry2w74rTCfVppy7fAFElsbR4NkhbnEC9Di/89X+WORAE4b+EWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:12:42Z"
    mac: ENC[AES256_GCM,data:p1hxh5tinak1kYHEhTZ+x8ttNJndVHq4LRy7ZJ+MJYM1NarFjnNlCCiJKxAcX7xxY5V056k7xhU+D3pzfkt2wZsZsfMVrz9V6e9QGwW9ZIrWrgAwQnznufwpnqJLZKbYat3/6uY0fQHyIOuOtmLAJ7Q0xdhp9UMpIo0QogUdH80=,iv:2g3aG7mQBvYsjkS8cPcKPasmdFQMli7Tn54ZLtnvbDI=,tag:HU2opvePSBkrD3BExLOZhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
