healthcheck: ENC[AES256_GCM,data:wtdCKHkMZ63XcSRb0AT6R5ZMqFMbvV7kvece8uZPYMajFh8MxI7pUhFVeRroWeZ8jp7LVWaqIi0=,iv:j8zVOlwApas40KN/JU2l9GoZJ/196AwMJlq9Jjl8f0w=,tag:0bSD+j5sfrknOsAOGbg91A==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:DekqZd0uhZxw0eiP8EDmHyoO+p4G7k0MeO0zbKGDqTdUBYCO,iv:Loshuy4FYKLboNaDmg2gedkDSAY+xgVJu7e8yYDSuek=,tag:Ki/5s+8fUo3G9kb6WYG5Cg==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSFY4WjdSNUNZV2FsZWln
            ZEE5TVBjcU5HalJKNS91NTF4c3lSclg0VDJNCnJyeFR2WFJxeHBkWGh1M0x0aFV0
            a0tDTWh2OGROWEhJWC9PaEg5Lzg4ODAKLS0tIEdvZHBVb2F4dGdmSXFPSEV5QjhJ
            emJwYk1lN0FXejd4dFJibG9TdnNsZGMKGdXCjUL+BmUB266//PZ/GCVlQ4mddZ5I
            S1cFYzqAJntA316GDio3GWlsc6vwcHMYmP2+AhiVR02+ESuL4yYRHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T18:36:33Z"
    mac: ENC[AES256_GCM,data:3i1BFpSPNhb+Q1UA5mI1qWr5huuRS6A8iAIaKZkcwMwL2uSBUeqp6YCbyF5P3I4ozKmPeRfBn6zZOFN7zQEJttFfkhZcAOFKug5/dT4ZgGoR2PRpn+h8/9qVjhzPEPFz7Jg8UDUOPcKbpadwQ+PwM7VlELVhM0CsKRF1oGWNt6M=,iv:cQEIlKqsKhG4kJGgQIUS4Yp9Y9JgRfMIMoAsXVk865Q=,tag:0UZQJdyRRFco5B7uZL7A0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
