healthcheck: ENC[AES256_GCM,data:AKN4w+MuDBuA55dy1CErWMej86NND55AMP3nkfHt14Sf45bkwrnCQAUEoyp4GY7cXt8u6wTeK+M=,iv:/IvMQZo/pL6D3Szeu44XCBoElduiEniJigN5dF9haYw=,tag:NIGgYoxpdBAd4RCQ2lZhMg==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:mlQle4lCZPBRkSVU41ZDbMlSDAv5wXCxQl/X9jNYrzdJ6ptN,iv:t/0nlrojOBlr87W2GgEKsEsWGrOs92MIEZANtUvWDZg=,tag:40PnTWCRrGlbnjXgMazO9g==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2JxeFFCaDFhdVdYNWFO
            QldycjNQMmNVVk1IZWw3djBCV3RKa3IwVEhZCkdhT25VbWlCNnBneE1JRDNheU1Z
            eVZTWFZ1SnFQYmsrNnhWQ3E3azVyRjgKLS0tIHRmSXNrZVpwVW1nZkZOK3k4d0RP
            allwbnF4RHN5OHlBNEVGcm80bHIvb28Kdfpdi3He0/zhA6zfwX1lFcuR77zoamhn
            o08TjouC8xKPcseOBS4k88DKYXUXHmWp8iJhW05H4ft5v81lyxKBYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:12:03Z"
    mac: ENC[AES256_GCM,data:3W7maHVZWaFBtt5vfhSwgFg5X8ETW1wm1YCpbypxJz1H0ccV4kwi7Kz69PWBSomMIlkHAdDpME3nGq7bmxdKW8uKUa9ZyGBEwUeuTjdjIUcXokwj3BSZDD70nwSYnVbFckhKskeNajj6DQsKVax09dqnsY4OzwRQs4VPeLZCwhQ=,iv:PIe+7SGrqJY0nqXVHn3tlRGnu5BrH3B1s4N1pkkWfbw=,tag:4xEa3MhTq8QCCnlY+9XzQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
