healthcheck: ENC[AES256_GCM,data:6oVm3inEb+OEG/+efvXdnb+KJFBHIP90unOeFWXnVwUV2bJbLLm4ZCjuC8lIeU5kJEIHPJDz9t4=,iv:ob13rzc570gdy6fK37bLdF+aa9t4lDwpw8Dj/MYHvjI=,tag:VfZM1dmDKVd6OGeguxRFGQ==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:zXOjM0yRSBfZqRvXBeXdtdDkw0P9f5vbo+s761h6V6y2TjfE,iv:fhAUEyW8i70OCQB4PjIToANmB1Ggh4hDZ7XxhGoH8bs=,tag:tCHooGrAkZDcvihnqkcZkw==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzdOT1NPQUg0NGdBalJI
            NGJnVFVlQmk2ckxsRnJGWTdnRGxMU2dlOVJvCjlRRlZnMlFrcmZWQWN4MzMwb2Vo
            MElEc2VtQUs4Z2VOazEyZVB0a3pQTWMKLS0tIGVoRXJraG14N1YzSGw1VHpQbk16
            RFFFL1JTVk82aXRDVURaMTNoQ1E3WG8KE9uPKR5ZM/jrrtNoT8mHo7yfJYqbIgTz
            xgoT1fiNEFL9I4jek1J17FJ7FkqGvUXo1+hnodlDv9dy9/bQz1F9zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:12:16Z"
    mac: ENC[AES256_GCM,data:dkk9k/HuBdS+QXGljD6o1a+ExH05WFFR/pxdtjhlLOodd7CYXoFoXVyN+e2/cLL3JtUAIexOL0/0OQOmh5dMv0qcOEwil92Dl9bZ3sLyrgT+EFT5WDNZDsfCXoJAfHcC/JQ3pCnsYTrZxeyCweMiCjEXBCGu7F86CCtkmY4G++g=,iv:xLFNVgLAQhlP8Y6GNyxMJRnp+ckyNciDx6GJ3qiMNDU=,tag:7lXa2Ay1xmNchyje2cBW7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
