healthcheck: ENC[AES256_GCM,data:cHfH9uAgjiLWocVmC5qXP5mlYfZJBgvfkZSQbf21TELkc2+qXL8/0YkXdzhGRNRJF7SBJs1QSfU=,iv:thrCPiprP3gwgRslWg6pxPwszeY/rqPhW3YtZQ45ZMU=,tag:UyP3ZpCkqCtFr49yeFTn1g==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:89VwkgXppRcn1bzL5pd/CrU2SeIccs23MfA7l4sRbX6Ivu7E,iv:Qn0ZhjiNney/UvBcu3u4vt2EEQ0R2VOPkEGicUAgE2c=,tag:pUX14lCPXoZUE4pBu/YV4A==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aW1NclRES1NQTVhLMGZK
            dXhKdW1CWFZGQjF6dERJS0RRY2dBdndocWlVCjYyL2FtTEFxL1Q0NXNLL2lQT1k1
            U1Zod0Fja2xDZGVudlNQSHdBaWwxbWsKLS0tIFFMUklzMjFnRmhYMTdUeEl6Mi81
            S0h1MlB6dUJhQ0thVndJNzJZNFd0Mk0KqtLNWGMjbgALTQMpfwJcMEaqEWUcScwY
            AfSswSl8MRh3IFiWkPZc6iKQvfhqV4RV4d36sMlXaEd5jrM2cljYLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:13:34Z"
    mac: ENC[AES256_GCM,data:m/CBs+M0Ao+FJip+EfpUx39+s2YOIW6zHwErPWI6iyz/rw0qAQfzmkOor1ET+CC2Xzh2Dbv8yCqKj+9UEJUs9ixGHEy+VPiyuFDt+anTbNyPimofTWKuCudKmOk9ZjHnGsUcWr5DZ2ziI5siDB4dlH26PHbZ1/RjBeBNTYTZ2Uc=,iv:He1MZA8Fug/Aklh8zzDTa5Xb8u+1ZCDAyii5spmMh8k=,tag:sghIE2XSJUM+GapNgvkAow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
