healthcheck: ENC[AES256_GCM,data:hdg94vnFlQ0o4lgfcAy1ccL9Khdpua094G6eAjAfOeX+hzBzFeNLryEUqbQpXp/yn4jmMGnM798=,iv:JKfM63eZlPx3iZe7XCF/Trx52yl7ht02CixNJ645/38=,tag:awVNXMRvzZzA1fbmy+sQNw==,type:str]
netbird_setup_key: ENC[AES256_GCM,data:UWf6e+dN5y6LZ77Fe42a/NhCv/eeYfHi3kQnmy5Llv/G+SaW,iv:ZN/QDL+uiOTfQnNxzry9LnDHvztIy19e+9m+wnDGJ1E=,tag:etYU381GDBDzgGzYGNvv1A==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWk5ySDlRNnk5T2ZMNjNH
            SEtEOHE5OVByUFJ1NmRadnJERkJuY0h4dEZJCkZkTEdLWnpuVEkxamQ4dGUzeW8r
            RXRJakt4blg0R0R5bTQzNGY4cnZIdE0KLS0tIGR3aEpkMHVHSmdZbHpVb1FGN05K
            U3BFSkFWQk9aTWFmV1RDRDNXYm45UlUK2M8j1I9plqUrC+AF79IiNd5mWO+aRwus
            4UzfskKa+xZhmf+VmCQnSi4NDLgWrFo/Snl3A5SfRrJlnBj1NkJZFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:13:44Z"
    mac: ENC[AES256_GCM,data:n1MPo4OoAwY+KubECN3ZDCEpfqZUAyG8cJy31zt1jCqxBl7KjVheZa4DFkHGVWTBH5TlMW+ixPY5RE+xGbHVxvpKD2KfCjOnHiUz6zDOe24p7S+D/RCgqe/k/9s80EjeAzcOyp2kjeRTTDFl61BxvfGFZPHkIJXzBCF1HoBZX+w=,iv:bUSoPtaJXzzoI7jPd9eWqCtNT+a5U+Si+p8b3UXdRUc=,tag:flBnUt2TBHGX+on9s9iVBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
