netbird_setup_key: ENC[AES256_GCM,data:uJ3GGbH7Fb6a82gIc9zMeYtW9ph7NxfPvWmnssCOmc8js9Xi,iv:oJsceRVUUmRfBeKVJ6mKiU7T05Wjcu78BuO1vXi3GKw=,tag:mWd3cAl5X5IeGwqb7gHVOQ==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROGo5TFJtZGI5VlN4clBm
            NmdMMUxTSFU1RTArVjBQemxTUU5LaFpuNlVBCmJxRXdGb2ZlWFNWZVBVSUZ4bC8w
            TnBlOVBSTGFzM2dSZ0QzL3ZUYy8wZzAKLS0tIFAyRFNsOXJXSFdtWXhLdkVkVXlq
            VjZWcEUyU2NDaWFtZlIzK2VWV1AzUWsKyR65yG9B2tFEpk318b3b4IfIiseWAKqR
            7tH/kxP34Np/oFo8SUlNQYhvO63YfTdZcECXaDAHNM14mgDqgTr1Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:13:54Z"
    mac: ENC[AES256_GCM,data:KK5csvTWxyUTfoVXgOcn10SXt7EvmF+CKk/8N0YjcpyuJJYhLzOILcMblvxBMgpBd4juUwVXI6oTayDNVxmntBsnaK2pQGbUt81Xuaq7ip4RGw9WDreWCEzmFfRyY838ZX8X19BTh42skwC2BmYOzTcu8GGDtB+25nNWkUZ6kUU=,iv:492Zyh/VfOyIMfAgHajo41Ey+spjkhHO5MKaLh+WxaM=,tag:z73HnWJdeEZrfZIia1NOcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
