netbird_setup_key: ENC[AES256_GCM,data:J7/YdeAlWF+zoa593lWG4AJmrIfPoiWqOJ09R3QLIBMWa8rm,iv:jBh7pe4cdZzsCs+lht+aIDOcW6jgHjrrB2MgjKzgBR4=,tag:Eo0lqZpUTBWmKxgmYLVXaA==,type:str]
sops:
    age:
        - recipient: age1hvnnk2zl3ygs4ya3az7j0z2pktpftheypu8ykkwwh3qvdjue4scsmf4zax
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTXlUc1ZRU3RXeUFNZlI0
            TnVXR2JmeEdZMXdxend6bEtsOEZpU0dEbWlNCjV3SHZUdXpLcHdDdGpaNW9RNmNH
            aTd3QUI5UWhRd2VLSGNFZEdNRzUrUFEKLS0tICs2Rk11eXpiWWxDY1JKVE5rcmg4
            NGw4Z0h4Z05ZNjVOdFE3clcwUnlMdmsKdRjMm6lnlZlL1m/H3B3wl9JBkbagPu3Z
            eLnUAJ+K/oPJiqkM6oyWKqJBeFzcABHnDvoMiESf3gTdwT6L7rpmAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T21:14:06Z"
    mac: ENC[AES256_GCM,data:p23OqnkiwhOsb8e3vYnA/q70TTZRGxM69g76xHtkGkGa8pJdFgUVxfFkQFqj1xBgq6Dx889x3BoR+7LxzABFdZCju6n5HpG7XLZCuotNh6tzwb0FiSMfFiJQkGDbqk1rzpcFrGRczhmaDdxXrEaCSpFFkU/KCNmxUSTV8NvGqO0=,iv:TyCqO4/t+uJ3Thgt5sOpCEODyDWxHTniKrp6mGr/TE8=,tag:ZbbmcYnY6E7Tq7irwSXoSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
