apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-organizr-user-auth-public@kubernetescrd,media-plex@kubernetescrd,media-plex-prefix@kubernetescrd
  name: plex-subdir
spec:
  ingressClassName: public
  rules:
  - host: plexmox.com
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 32400
        path: /plex/
        pathType: Prefix
  tls:
  - hosts:
    - plexmox.com
    secretName: plexmox-com-tls
