apiVersion: v2
name: nack
description: nack manifests
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: nack
    version: 0.33.2
    repository: https://nats-io.github.io/k8s/helm/charts/
