generic:
  nameOverride: seerr
  fullnameOverride: seerr

  replicaCount: 1

  image:
    repository: ghcr.io/seerr-team/seerr
    pullPolicy: IfNotPresent
    tag: develop@sha256:0912c85b89df6c4d9a916fed43a8250d4f1a9e8f23be54d2b8e5081081e98adc

  service:
    port: 5055

  resources:
    requests:
      cpu: 50m
      memory: 256Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  httpRoute:
    enabled: true
    labels:
      traefik-instance: public
    hostnames: [overseerr.plexmox.com]
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: public
        namespace: traefik
    rules:
      - port: 5055
        matches:
          - path:
              type: PathPrefix
              value: /
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: seerr

  # entrypoint:
  #   command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]

  pvc:
    enabled: true
    mountPath: /app/config
    storageClassName: longhorn
    size: 1Gi

  deploymentStrategy:
    type: Recreate

  probes:
    type: tcpSocket
    options:
      port: http

    initialDelaySeconds: 20

  config:
    TZ: Europe/London
