apiVersion: v2
name: netbird-operator
description: netbird-operator chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kubernetes-operator
    alias: netbird-operator
    repository: https://netbirdio.github.io/helms
    version: 0.2.1
