netbird-operator:
  operator:
    image:
      repository: netbirdio/kubernetes-operator
      tag: 0.2.1

  ingress:
    enabled: true
    router:
      enabled: true

  cluster:
    name: k3s-cluster

  managementURL: https://netbird.plexmox.com

  netbirdAPI:
    keyFromSecret:
      name: netbird-operator-secrets
      key: api-token
