apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - haproxy.yaml
  - node-exporter.yaml
  - process-exporter.yaml
  - smartctl-exporter.yaml
  - pve.yaml
  - k8s-annotations.yaml
  - keepalived.yaml
  - minio.yaml
  - adguard.yaml
  - blackbox.yaml
  - garage.yaml
