apiVersion: v2
name: coredns
description: coredns chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 37.3.0
