apiVersion: v3
name: external-dns
version: v1.0.0

dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    alias: adguard-1
    version: 1.20.0
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    alias: adguard-2
    version: 1.20.0
