apiVersion: v2
name: coredns
description: coredns chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: coredns
    repository: https://coredns.github.io/helm
    version: 1.42.1
