---
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_version: v1.35.1+k3s1

k3s_state: installed

k3s_become: true

k3s_server_args: ""

k3s_agent_args: ""

k3s_kubelet_args: []

k3s_kube_apiserver_args: []

k3s_kube_scheduler_args: []

k3s_kube_controller_manager_args: []

k3s_server_url: ""

k3s_tls_san: []

k3s_disable: []

k3s_expose_etcd_metrics: false

k3s_flannel_backend: vxlan

k3s_disable_kube_proxy: false

k3s_disable_network_policy: false

k3s_cluster_cidr: "10.42.0.0/16"

k3s_service_cidr: "10.43.0.0/16"

k3s_write_kubeconfig_mode: "644"

k3s_taints: []

k3s_registry_enabled: false
k3s_registry_username: ""
k3s_registry_password: ""
