apiVersion: v2
name: crowdsec
description: crowdsec chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: crowdsec
    repository: https://crowdsecurity.github.io/helm-charts
    version: 0.20.1
