apiVersion: v2
name: traefik-crds
description: traefik-crds chart
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: traefik-crds
    repository: https://traefik.github.io/charts
    version: 1.14.0
