apiVersion: v2
name: cloudflare-origin-certs
description: cloudflare-origin-certs chart
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: origin-ca-issuer
    alias: cloudflare
    version: "0.6.2"
    repository: oci://ghcr.io/cloudflare/origin-ca-issuer-charts
