---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/k8s.mariadb.com/database_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: booklore
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: booklore-creds
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: booklore
spec:
  name: booklore
  host: "%"
  passwordSecretKeyRef:
    name: booklore-creds
    key: db-password
  mariaDbRef:
    name: mariadb
    namespace: mariadb
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/k8s.mariadb.com/grant_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: booklore-grant
spec:
  database: booklore
  table: "*"
  privileges: [ALL]
  username: booklore
  mariaDbRef:
    name: mariadb
    namespace: mariadb
