apiVersion: v2
name: crunchy-userinit
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: crunchy-users-helm
    version: "1.0.8"
    repository: oci://ghcr.io/henrywhitaker3
