middlewares:
  authelia:
    namespaces:
      - media
      - misc
      - traefik
      - docs
      - monitoring
      - default
      - istio-system
  organizr:
    namespaces:
      - media
      - traefik
