apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.3
    namespace: istio-system
  - name: istiod
    releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.2
    namespace: istio-system
    valuesFile: istiod.yaml
  - name: cni
    releaseName: istio-cni
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.2
    namespace: istio-system
    valuesFile: cni.yaml
  - name: ztunnel
    releaseName: istio-ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.2
    namespace: istio-system
