---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-kgateway
  namespace: gateways
spec:
  gatewayClassName: kgateway
  infrastructure:
    annotations:
      metallb.io/loadBalancerIPs: 10.0.0.25
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: "*.henrywhitaker.com"
      name: henrywhitaker
      port: 8443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-henrywhitaker-com-tls
            namespace: gateways
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.plexmox.com"
      name: plexmox
      port: 8443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-plexmox-com-tls
            namespace: gateways
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: "*.synthetigo.com"
      name: syntehtigo
      port: 8443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-synthetigo-dev-tls
            namespace: gateways
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: Same
      name: web
      port: 8000
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: "*.yourbuild.com"
      name: yourbuild
      port: 8443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-yourbuild-dev-tls
            namespace: gateways
        mode: Terminate
