---
middlewares:
  authelia:
    namespaces:
      - name: media
        http:
          - booklore
      - name: misc
        http:
          - garage-webui
          - speedtest
      - name: docs
        http:
          - outline
      - name: monitoring
        http:
          - grafana
          - kube-prometheus-stack-alertmanager
          - vm-metrics
          - uptime-kuma
      - name: immich
        http:
          - immich-server
      - name: harbor
        http:
          - harbor-route
      - name: default
        http:
          - unraid

  organizr:
    namespaces:
      - name: media
        http:
          - prowlarr
          - radarr
          - tautulli
          - transmission
          - booklore-agentgateway
