apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno

helmCharts:
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    version: "3.7.0"
    repo: https://kyverno.github.io/kyverno
    valuesFile: values.yaml

resources:
  - https://github.com/kyverno/policies/pod-security
patches:
  - path: patches/apparmor.yaml
  - path: patches/policies.yaml
  - path: patches/clusterpolicies.yaml
