---
backgroundController:
  rbac:
    clusterRoles:
      extraResources:
        - apiGroups: [gateway.networking.k8s.io]
          resources: [gateways, httproutes]
          verbs: [get, list, watch]

features:
  logging:
    format: json

config:
  resourceFilters:
    - "[Event,*,*]"
    - "[*,kube-system,*]"
    - "[*,kube-public,*]"
    - "[*,kyverno,*]"
