apiVersion: v2
name: nats
description: nats manifests
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: nats
    version: 2.12.3
    repository: https://nats-io.github.io/k8s/helm/charts/
