generic:
  nameOverride: theme-park
  fullnameOverride: theme-park

  replicaCount: 3

  image:
    repository: ghcr.io/home-operations/theme-park
    pullPolicy: Always
    tag: "rolling"

  service:
    port: 8080

  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: theme-park.plexmox.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: theme-park-plexmox-com-tls
        hosts:
          - theme-park.plexmox.com

  resources:
    requests:
      cpu: 5m
      memory: 10Mi
    limits:
      memory: 50Mi
